#!/usr/bin/env node
'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = __dirname;
const CONTENT_DIR = path.join(ROOT, 'content');
const OUT         = path.join(ROOT, 'content.js');

// ─── File reader (returns '' if file missing) ─────────────────────────────────
function read(name) {
  const full = path.join(CONTENT_DIR, name);
  if (!fs.existsSync(full)) { console.warn('  (missing: content/' + name + ')'); return ''; }
  return fs.readFileSync(full, 'utf8');
}

// ─── Frontmatter block parser ─────────────────────────────────────────────────
// Parses a single "key: value" block into a plain object.
// - Strips surrounding quotes from values
// - Skips lines with empty keys or empty values
function parseFrontmatter(block) {
  const obj = {};
  for (const line of block.trim().split('\n')) {
    const colon = line.indexOf(':');
    if (colon === -1) continue;
    const key = line.slice(0, colon).trim();
    let val   = line.slice(colon + 1).trim();
    if (!key) continue;
    // strip surrounding quotes
    if (val.length >= 2 &&
        ((val.startsWith('"') && val.endsWith('"')) ||
         (val.startsWith("'") && val.endsWith("'")))) {
      val = val.slice(1, -1).trim();
    }
    if (!val) continue; // skip blank/empty values
    obj[key] = val;
  }
  return obj;
}

// ─── Multi-entry file parser ──────────────────────────────────────────────────
// Splits a file on "---" lines, parses each block as frontmatter.
// Returns an array of objects (skips empty blocks).
function parseMultiEntry(fileText) {
  if (!fileText.trim()) return [];
  return fileText
    .split(/^---[ \t]*$/m)
    .map(b => b.trim())
    .filter(b => b && !b.startsWith('#')) // skip comments / empty
    .map(parseFrontmatter)
    .filter(obj => Object.keys(obj).length > 0);
}

// ─── about.md: frontmatter + body ────────────────────────────────────────────
function parseAbout(fileText) {
  if (!fileText.trim()) return { github: '', bio: '' };
  const parts = fileText.split(/^---[ \t]*$/m);
  // Expected: parts[0]='' parts[1]=frontmatter parts[2]=body
  const fm   = parseFrontmatter(parts[1] || '');
  const body = (parts[2] || '').trim().replace(/\s+/g, ' ');
  return { github: fm.github || '', bio: body };
}

// ─── instagram.md: one URL per line, no frontmatter ──────────────────────────
function parseInstagram(fileText) {
  return fileText
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('#'));
}

// ─── Post-processors ─────────────────────────────────────────────────────────
function processProjects(raw) {
  return raw.map(r => {
    const out = Object.assign({}, r);
    if (out.tech) out.tech = out.tech.split(',').map(s => s.trim()).filter(Boolean);
    return out;
  });
}

function processBooks(raw) {
  return raw.map(r => {
    const out = Object.assign({}, r);
    if (out.stars) out.stars = parseInt(out.stars, 10) || out.stars;
    return out;
  });
}

// ─── Build ────────────────────────────────────────────────────────────────────
console.log('Building content.js...');

const about     = parseAbout(read('about.md'));
const projects  = processProjects(parseMultiEntry(read('projects.md')));
const blog      = parseMultiEntry(read('blog.md'));
const events    = parseMultiEntry(read('events.md'));
const speaking  = parseMultiEntry(read('speaking.md'));
const books     = processBooks(parseMultiEntry(read('books.md')));
const instagram = parseInstagram(read('instagram.md'));
const linkedin  = parseMultiEntry(read('linkedin.md'));

const siteContent = { bio: about.bio, projects, blog, events, speaking, books, instagram, linkedin };

const output = [
  '// AUTO-GENERATED by build.js — do not edit by hand.',
  '// Run:  node build.js',
  '',
  'var GITHUB_USERNAME = ' + JSON.stringify(about.github) + ';',
  '',
  'var SITE_CONTENT = ' + JSON.stringify(siteContent, null, 2) + ';',
  '',
].join('\n');

fs.writeFileSync(OUT, output, 'utf8');
console.log('✓ content.js built (' + output.length + ' bytes)');
