// AUTO-GENERATED by build.js — do not edit by hand.
// Run:  node build.js

var GITHUB_USERNAME = "jordanleopold";

var SITE_CONTENT = {
  "bio": "Jordan Leopold is an entrepreneur, venture capital professional, and political advocate based in the San Francisco Bay Area. With a background spanning enterprise sales, early-stage investing, and government affairs, he is currently building CLIENTEL — an agentic AI platform enabling the one-man sales team — while teaching himself software development.",
  "projects": [
    {
      "name": "Startup IQ",
      "desc": "Relationship management platform helping early-stage founders identify investors and catalyze their network into closed funding rounds through live data and AI.",
      "current": true,
      "tech": [
        "Network",
        "React",
        "Node.js"
      ]
    },
    {
      "name": "21st CENTURION",
      "desc": "Agentic AI Platform for startup founders, teams and small enterprises.",
      "current": true,
      "tech": [
        "AI",
        "Node.js"
      ]
    },
    {
      "name": "Agentic AI Workshop",
      "desc": "Everything Jordan has learned relating to fullstack agentic AI development.",
      "repo": "agentic-ai-workshop",
      "github": true
    },
    {
      "name": "Claude Code Skills Distilled",
      "desc": "42 production-quality Claude Code skills distilled from 17 community repositories.",
      "repo": "claude-code-skills-distilled",
      "github": true
    },
    {
      "name": "MediaBay",
      "desc": "Open source online video downloader and editor. Not currently functioning — work in progress.",
      "repo": "mediabay",
      "github": true
    },
    {
      "name": "People of Change",
      "desc": "Founded grassroots organization providing baseline needs through community service, having conversations about community issues for policy change.",
      "past": true
    },
    {
      "name": "Haycocoa",
      "desc": "Hayward Community Coalition using political education and community activation for local policy change.",
      "past": true
    },
    {
      "name": "Kinoir",
      "desc": "Fashionable skincare for men with melanin.",
      "past": true
    },
    {
      "name": "Hero Ring",
      "desc": "Smart ring for women to discreetly send a local emergency signal.",
      "past": true
    },
    {
      "name": "Plexys",
      "desc": "Political campaign platform to direct followers towards political action online.",
      "past": true
    },
    {
      "name": "UniChain",
      "desc": "Blockchain based degree unit system for universities.",
      "past": true
    }
  ],
  "blog": [],
  "events": [],
  "speaking": [],
  "books": [
    {
      "title": "Zero to One",
      "author": "Peter Thiel",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "The Lean Startup",
      "author": "Eric Ries",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Creativity, Inc.",
      "author": "Ed Catmull",
      "year": "2014",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Elon Musk",
      "author": "Walter Isaacson",
      "year": "2023",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "The Startup Community Way",
      "author": "Brad Feld & Ian Hathaway",
      "year": "2020",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Anything You Want",
      "author": "Derek Sivers",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Business Model Generation",
      "author": "Alexander Osterwalder & Yves Pigneur",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Hope for Film",
      "author": "Ted Hope",
      "year": "2014",
      "status": "read",
      "subject": "Business",
      "subsubject": "Entrepreneurship"
    },
    {
      "title": "Commercial Real Estate Investing for Dummies",
      "author": "Peter Conti & Peter Harris",
      "year": "2022",
      "status": "read",
      "subject": "Business",
      "subsubject": "Investing & Finance"
    },
    {
      "title": "The Big Short",
      "author": "Michael Lewis",
      "year": "2010",
      "status": "read",
      "subject": "Business",
      "subsubject": "Investing & Finance"
    },
    {
      "title": "End the Fed",
      "author": "Ron Paul",
      "year": "2009",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Political Theory"
    },
    {
      "title": "Equity Asset Valuation",
      "author": "Jerald E. Pinto",
      "edition": "3rd",
      "status": "read",
      "subject": "Business",
      "subsubject": "Investing & Finance"
    },
    {
      "title": "Core Interview Secrets",
      "author": "Victor Cheng",
      "year": "2011",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "Crack the Case System",
      "author": "David Ohvali",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "Crack the Case System for Experienced Hires",
      "author": "David Ohvali",
      "year": "2012",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "How to Win Friends and Influence People",
      "author": "Dale Carnegie",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "How to Win Friends and Influence People in the Digital Age",
      "author": "Dale Carnegie",
      "year": "2011",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "Connecting Beyond the Name Tag",
      "author": "William N. Sadwicky",
      "status": "read",
      "subject": "Business",
      "subsubject": "Sales & Career"
    },
    {
      "title": "Managing to Change the World",
      "author": "Alison Green",
      "year": "2012",
      "status": "read",
      "subject": "Business",
      "subsubject": "Strategy & Management"
    },
    {
      "title": "127 Mental Toughness Secrets of the World Class",
      "author": "Steve Siebold",
      "year": "2005",
      "status": "read",
      "subject": "Business",
      "subsubject": "Strategy & Management"
    },
    {
      "title": "The Design of Everyday Things",
      "author": "Don Norman",
      "status": "read",
      "subject": "Business",
      "subsubject": "Strategy & Management"
    },
    {
      "title": "Outwitting the Devil",
      "author": "Napoleon Hill",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Mindset"
    },
    {
      "title": "A New Earth",
      "author": "Eckhart Tolle",
      "year": "2005",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Mindset"
    },
    {
      "title": "Finish",
      "author": "Jon Acuff",
      "year": "2017",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Mindset"
    },
    {
      "title": "The 50th Law",
      "author": "50 Cent & Robert Greene",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Mindset"
    },
    {
      "title": "Landmark Insights: Conversations That Matter",
      "year": "2016",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Mindset"
    },
    {
      "title": "How to Stop Worrying and Start Living",
      "author": "Dale Carnegie",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Habits & Productivity"
    },
    {
      "title": "Deep Work",
      "author": "Cal Newport",
      "year": "2016",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Habits & Productivity"
    },
    {
      "title": "Memory",
      "author": "Douglas J. Herrmann",
      "year": "1990",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Habits & Productivity"
    },
    {
      "title": "The 5 Essential People Skills",
      "author": "Dale Carnegie",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Relationships"
    },
    {
      "title": "The 5 Love Languages",
      "author": "Gary Chapman",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Relationships"
    },
    {
      "title": "How to Be a Person",
      "author": "Lindy West & Dan Savage",
      "year": "2012",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Relationships"
    },
    {
      "title": "Please Understand Me II",
      "author": "David Keirsey",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Relationships"
    },
    {
      "title": "The Body Sculpting Bible for Men",
      "author": "James Villepigue & Hugo Rivera",
      "status": "read",
      "subject": "Personal Dev",
      "subsubject": "Health & Fitness"
    },
    {
      "title": "Meditations",
      "author": "Marcus Aurelius",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Classical"
    },
    {
      "title": "The Art of War",
      "author": "Sun Tzu",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "The Book of Five Rings",
      "author": "Miyamoto Musashi",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Musashi's Dokkodo",
      "author": "Miyamoto Musashi",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Letters from a Stoic",
      "author": "Seneca",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Classical"
    },
    {
      "title": "Capitalism: The Unknown Ideal",
      "author": "Ayn Rand",
      "year": "1966",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Classical"
    },
    {
      "title": "The Fountainhead",
      "author": "Ayn Rand",
      "year": "1943",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Classical"
    },
    {
      "title": "The Dhammapada",
      "author": "Buddha",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Buddhism 101",
      "author": "Arnie Kozak",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "The Life of Sariputta",
      "author": "Thera Nyanaponika",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Tao Te Ching",
      "author": "Lao Tzu",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "The Book",
      "author": "Alan Watts",
      "year": "1966",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Living Buddha, Living Christ",
      "author": "Thich Nhat Hanh",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "I Ching: The Book of Change",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "Journey to the West",
      "author": "Wu Cheng-En",
      "year": "2021",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "The Tao of Leadership",
      "author": "John Heider",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Eastern"
    },
    {
      "title": "The Power of Now: A Guide to Spiritual Enlightenment",
      "author": "Eckhart Tolle",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Spirituality"
    },
    {
      "title": "How to Manifest",
      "author": "Pema Chödrön",
      "year": "2019",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Spirituality"
    },
    {
      "title": "Remember, Be Here Now",
      "author": "Ram Dass",
      "year": "1978",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Spirituality"
    },
    {
      "title": "Physics of the Impossible",
      "author": "Michio Kaku",
      "year": "2008",
      "status": "read",
      "subject": "Philosophy",
      "subsubject": "Spirituality"
    },
    {
      "title": "Napoleon: A Life",
      "author": "Andrew Roberts",
      "year": "2014",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "The Autobiography of Malcolm X",
      "author": "Malcolm X & Alex Haley",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "Black Boy",
      "author": "Richard Wright",
      "year": "1945",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "The Diary of a Young Girl",
      "author": "Anne Frank",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "A Long Way Gone",
      "author": "Ishmael Beah",
      "year": "2007",
      "status": "read",
      "subject": "History",
      "subsubject": "Biography"
    },
    {
      "title": "Sapiens: A Brief History of Humankind",
      "author": "Yuval Noah Harari",
      "status": "read",
      "subject": "History",
      "subsubject": "World History"
    },
    {
      "title": "The Labyrinths of Solitude",
      "author": "Octavio Paz",
      "status": "read",
      "subject": "History",
      "subsubject": "World History"
    },
    {
      "title": "Black Against Empire",
      "author": "Joshua Bloom & Waldo E. Martin",
      "year": "2013",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "Black Liberation and Socialism",
      "author": "Ahmed Shawki",
      "year": "2016",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "How We Got Free",
      "author": "Keeanga-Yamahtta Taylor",
      "year": "2017",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "The Black Panthers Speak",
      "author": "Philip S. Foner",
      "year": "2014",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "In Search of the Black Fantastic",
      "author": "Richard Iton",
      "year": "2008",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "How Change Happens",
      "author": "Leslie R. Crutchfield",
      "year": "2018",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Social Justice"
    },
    {
      "title": "Capitalism vs. Collectivism",
      "author": "Marcus D. Follmann",
      "year": "2013",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Political Theory"
    },
    {
      "title": "The Iran Agenda",
      "author": "Reese Erlich",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Political Theory"
    },
    {
      "title": "Environmental Ethics",
      "author": "Andrew Karolindes",
      "year": "2012",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Political Theory"
    },
    {
      "title": "Dangerous Convictions",
      "author": "Rod Unsworth",
      "status": "read",
      "subject": "Politics",
      "subsubject": "Political Theory"
    },
    {
      "title": "Fight Club",
      "author": "Chuck Palahniuk",
      "year": "1996",
      "status": "read",
      "subject": "Fiction",
      "subsubject": "Contemporary"
    },
    {
      "title": "The Last of the Mohicans",
      "author": "James Fenimore Cooper",
      "year": "1826",
      "status": "read",
      "subject": "Fiction",
      "subsubject": "Classic"
    },
    {
      "title": "Me Talk Pretty One Day",
      "author": "David Sedaris",
      "status": "read",
      "subject": "Fiction",
      "subsubject": "Humor & Memoir"
    },
    {
      "title": "Principles of Marketing",
      "author": "Philip Kotler, Gary Armstrong & Marc Oliver Opresnik",
      "edition": "18th Global",
      "year": "2020",
      "status": "textbook",
      "subject": "Business"
    },
    {
      "title": "Public Finance and Public Policy",
      "author": "Jonathan Gruber",
      "edition": "6th",
      "year": "2019",
      "status": "textbook",
      "subject": "Policy"
    },
    {
      "title": "A Brief Atlas of the Human Body",
      "author": "Matt Hutchinson",
      "edition": "2nd",
      "year": "2008",
      "status": "textbook",
      "subject": "Science"
    },
    {
      "title": "A History of Economic Theory and Method",
      "author": "Robert B. Ekelund Jr. & Robert F. Hébert",
      "edition": "6th",
      "year": "2014",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "A Practical Guide for Policy Analysis: The Eightfold Path",
      "author": "Eugene Bardach & Eric M. Patashnik",
      "year": "2019",
      "status": "textbook",
      "subject": "Policy"
    },
    {
      "title": "American Political Thought",
      "author": "Michael S. Cummings",
      "edition": "7th",
      "year": "2019",
      "status": "textbook",
      "subject": "Policy"
    },
    {
      "title": "An Introduction to International Economics",
      "author": "Kenneth A. Reinert",
      "edition": "1st",
      "year": "2011",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Aspects of Western Civilizations, Vol. 1",
      "author": "Perry M. Rogers",
      "edition": "8th",
      "year": "2008",
      "status": "textbook",
      "subject": "History"
    },
    {
      "title": "Aspects of Western Civilizations, Vol. 2",
      "author": "Perry M. Rogers",
      "year": "2008",
      "status": "textbook",
      "subject": "History"
    },
    {
      "title": "Computers Are Your Future Complete",
      "edition": "11th",
      "year": "2014",
      "author": "Longshore & Parsons",
      "status": "textbook",
      "subject": "Technology"
    },
    {
      "title": "Coursebook to Accompany Microeconomics Private and Public",
      "author": "James O. Gwartney",
      "year": "2013",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Essentials of Corporate Finance",
      "author": "Stephen A. Ross, Randolph W. Westerfield & Bradford D. Jordan",
      "status": "textbook",
      "subject": "Finance"
    },
    {
      "title": "Games and Information: An Introduction to Game Theory",
      "author": "Eric Rasmusen",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Governing California in the Twenty-First Century",
      "author": "J. Theodore Anagnoson",
      "status": "textbook",
      "subject": "Policy"
    },
    {
      "title": "How Things Work: The Physics of Everyday Life",
      "author": "Louis A. Bloomfield",
      "edition": "6th",
      "year": "2015",
      "status": "textbook",
      "subject": "Science"
    },
    {
      "title": "Human Anatomy & Physiology",
      "author": "Elaine N. Marieb & Katja N. Hoehn",
      "edition": "10th",
      "year": "2022",
      "status": "textbook",
      "subject": "Science"
    },
    {
      "title": "Introduction to Econometrics",
      "author": "James H. Stock & Mark W. Watson",
      "edition": "4th Updated",
      "year": "2015",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Investments",
      "author": "Frank K. Reilly & Edgar A. Norton",
      "edition": "7th",
      "year": "2007",
      "status": "textbook",
      "subject": "Finance"
    },
    {
      "title": "Macroeconomics",
      "author": "Andrew B. Abel, Ben Bernanke & Dean Croushore",
      "edition": "8th",
      "year": "2013",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Macroeconomics, Global Edition",
      "author": "Andrew B. Abel, Ben S. Bernanke & Dean Croushore",
      "edition": "11th Global",
      "year": "2023",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Macroeconomics",
      "author": "Stephen Williamson",
      "edition": "6th",
      "year": "2016",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Microeconomics: Theory and Applications with Calculus",
      "author": "Jeffrey M. Perloff",
      "edition": "5th",
      "year": "2020",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Microeconomics",
      "author": "Jeffrey M. Perloff",
      "edition": "8th",
      "year": "2018",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Monetary Theory and Policy",
      "author": "Carl E. Walsh",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "Oceanography: An Invitation to Marine Science",
      "author": "Tom K. Garrison & Robert Ellis",
      "edition": "9th",
      "year": "2016",
      "status": "textbook",
      "subject": "Science"
    },
    {
      "title": "Organizational Behavior: Managing People and Organizations",
      "author": "Ricky W. Griffin, Jean M. Phillips & Stanley M. Gully",
      "edition": "13th",
      "year": "2019",
      "status": "textbook",
      "subject": "Business"
    },
    {
      "title": "Principles of Microeconomics",
      "author": "N. Gregory Mankiw",
      "edition": "10th",
      "year": "2024",
      "status": "textbook",
      "subject": "Economics"
    },
    {
      "title": "The Legal Environment Today",
      "author": "Roger LeRoy Miller",
      "edition": "10th",
      "year": "2021",
      "status": "textbook",
      "subject": "Business"
    },
    {
      "title": "Thermodynamics: An Engineering Approach",
      "author": "Yunus A. Cengel, Michael A. Boles & Mehmet Kanoglu",
      "edition": "9th",
      "year": "2019",
      "status": "textbook",
      "subject": "Science"
    }
  ],
  "instagram": [],
  "linkedin": []
};
